### ISSUE TITLE
"cycle" templatetag no longer lives in future

### ISSUE THREAD

**Issue by aogier** [litchfield/django-liststyle#12]
Hi, loading `cycle` from future leads to an error at least on django 1.10. Since this is anyway deprecated since 1.8 I'd suggest to simply remove the statement. Everything else work great under 1.10

I've sent a trivial PR here #11

many thanks, regards

**Comment by brianhhq** [comment]
Hi Aogier,

That is cool. Thank you.

I am new to Django. I got a question, How do you maintain the changed code?

for example, I put all my installed package into a file called requirements.txt. when I deploy, it will reinstall the package on production server. therefore, my change on the code will lost? How do you make sure the changes is always there.
Thanks in advance.

**Comment by aogier** [comment]
#11 merged, thank you
