### ISSUE TITLE
Don't mixins come first?

### ISSUE THREAD

**Issue by andybak** [litchfield/django-liststyle#4]
In the readme:

    class MyModelAdmin(admin.ModelAdmin, ListStyleAdminMixin):

I was under the impression it should be:

    class MyModelAdmin(ListStyleAdminMixin, admin.ModelAdmin):

(If I'm wrong I'd better go and check a huge bunch of my code!)

**Comment by litchfield** [comment]
Yep you're right, left to right. Thanks, I'll fix.
