### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by inoks** [litchfield/django-liststyle#8]
Seems does not works on Django 1.9.

**Comment by fabriceb** [comment]
Had a few issues myself, ended up making it work this way:

- pip install django-liststyle==0.2b
- be careful of the order in INSTALLED_APPS, liststyle must be before django.contrib.admin

Cheers.

Fabrice

**Comment by litchfield** [comment]
Thanks @inoks @fabriceb
